using UnityEngine;
using System.Collections;

using NLua;

public class ExampleBehaviour : LuaBaseMonoBehaviour
{

	public string source = @"
import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.


end



";

	string scriptString = @"
local Lib = {}
function Lib:Start()
	Debug.Log('in example start')
end

local Angle = Vector3.up;
local Speed = 5;

local showEnv = false
local envScroll = Vector2.zero

function Lib:Update()
	local transform = self.transform
	transform:RotateAround(transform.position,Angle,Speed * Time.deltaTime)

	if Input.GetKey(KeyCode.W) then
		Speed = Speed + 1
	end

	if Input.GetKey(KeyCode.S) then
		Speed = Speed - 1
	end

	if Input.GetKey(KeyCode.A) then
		Angle.z = Angle.z + 1
	end

	if Input.GetKey(KeyCode.D) then
		Angle.z = Angle.z - 1
	end
end

function Lib:OnGUI()
	GUILayout.BeginArea(Rect(10,10,(Screen.width / 2) - 20,Screen.height - 20))

	-- Adding '{ }' to the end of GUI functions satisfies their 'params' argument.
	GUILayout.Label('[W/S] Speed: ' .. Speed,{ }) 
	GUILayout.Label('[A/D] Rot Angle: ' .. Angle:ToString(),{ })

	GUILayout.EndArea()

	GUILayout.BeginArea(Rect((Screen.width / 2) + 10,10,(Screen.width / 2) - 20,Screen.height - 20))

	if GUILayout.Button('Show Enviroment',{ }) then
		showEnv = not showEnv
	end

	if showEnv then
		envScroll = GUILayout.BeginScrollView(envScroll,{ })
		for k, v in pairs(_G) do
			GUILayout.BeginHorizontal({ })

			GUILayout.Label(k,{ })
			GUILayout.FlexibleSpace()
			GUILayout.Label(tostring(v),{ })

			GUILayout.EndHorizontal()
		end
		GUILayout.EndScrollView()
	end	

	GUILayout.EndArea()
end

function Lib:test(arg1, arg2)
	Debug.Log('call example test success: ' .. arg1 .. ', ' .. arg2 )
	return 'thanks', 'ok'
end
return Lib
";

	Lua env;

	void Awake ()
	{
		InitLuaScriptString (scriptString);
	}

	void Start ()
	{
		Call ("Start");
	}
	
	void Update ()
	{
		Call ("Update");
	}

	void OnGUI ()
	{
		Call ("OnGUI");
	}

}
